env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

freebsd_instance:
  image_family: freebsd-13-0
  cpu: 4
  memory: 16G

task:
  timeout_in: 90m
  script:
    - ./build.sh
  binaries_artifacts:
    path: "_build/bhyve_enode.txz"  
