#!/bin/sh
PATH=/sbin:/bin
export PATH

case ${1##*/} in
    new_start_erl.data)
        START_ERL_DATA="$1"
        RELEASE_ROOT_DIR=${1%%/releases/new_start_erl.data}
    ;;
    *)
        RELEASE_ROOT_DIR=$1
        START_ERL_DATA="$RELEASE_ROOT_DIR/releases/start_erl.data"
    ;;
esac

read -r ERTS_VSN REL_VSN < "$START_ERL_DATA" || true
REL_NAME=${RELEASE_ROOT_DIR##*/}
REL_DIR="$RELEASE_ROOT_DIR/releases/$REL_VSN"
ERTS_DIR="$RELEASE_ROOT_DIR/erts-$ERTS_VSN"
SYS_CONFIG="$REL_DIR/sys.config"
VM_ARGS="$REL_DIR/vm.args"

export HOME="$RELEASE_ROOT_DIR"
export ROOTDIR="$RELEASE_ROOT_DIR"
export BINDIR="$ERTS_DIR/bin"
export EMU="beam"
export PROGNAME="erl"
ERTS_LIB_DIR="$ERTS_DIR/../lib"
[ -f "$REL_DIR/$REL_NAME.boot" ] && BOOTFILE="$REL_NAME" || BOOTFILE=start
cd "$ROOTDIR" || exit

export HEART_COMMAND="/etc/minit/heart_command"
export HEART_BEAT_TIMEOUT=30
export TERM=xterm

exec "$BINDIR"/erlexec -config "$SYS_CONFIG" -args_file "$VM_ARGS" \
     -mode embedded -boot_var ERTS_LIB_DIR "$ERTS_LIB_DIR" \
     -boot "$REL_DIR/$BOOTFILE" -sasl start_prg '"/etc/minit/softkill"' \
    <> /dev/ttyu0  >&0 2>&1
